# Generated by Django 4.1.2 on 2023-03-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='tri',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
