# Generated by Django 4.1.7 on 2023-03-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ImageField(blank=True, default='recettes/no-image.jpg', null=True, upload_to='recettes/'),
        ),
    ]
