# Generated by Django 4.1.2 on 2023-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_categorie_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/recettes'),
        ),
    ]
