# Generated by Django 4.1.7 on 2023-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_alter_categorie_slug_alter_recette_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
