# Generated by Django 4.1.7 on 2023-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0006_recette_commentaire_recette_cout_recette_difficulte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='tps_cuisson',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='tps_preparation',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='tps_repos',
        ),
        migrations.AddField(
            model_name='recette',
            name='tps_cuisson_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='tps_cuisson_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='tps_preparation_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='tps_preparation_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='tps_repos_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='tps_repos_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
