# Generated by Django 4.1.7 on 2023-03-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0007_remove_recette_tps_cuisson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='unite_quantite',
            field=models.CharField(blank=True, choices=[('pers', 'personnes'), ('g', 'grammes'), ('kg', 'kilogrammes'), ('l', 'litres'), ('ml', 'millilitres'), ('cl', 'centilitres'), ('cac', 'c. à café'), ('cas', 'c. à soupe')], max_length=5, null=True),
        ),
    ]
